name: udemy_proyect
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.36.0 
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  ionicons: ^0.2.2
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  line_awesome_flutter: ^1.0.1
  flutter_screenutil:  ^5.9.0
  email_validator: ^2.0.1
  string_validator: ^0.3.0
  image_picker: ^1.1.0 
  path_provider: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/icons/
